package store

import "time"

// SessionRecord maps to calc_sessions (ADR-REQ-010, Layer 1).
type SessionRecord struct {
	SessionID          int64 // auto-generated by MariaDB
	CreatedAt          time.Time
	EntryAssetID       string
	TargetAssetID      string
	MaxHops            int
	OrientationTime    float64
	SwitchoverTime     float64
	PriorityTolerance  int
	PathsFound         int
	AssetsRecalculated int
	QueryTimeMs        int
	TotalTimeMs        int
}

// PathRecord maps to calc_paths (ADR-REQ-011, Layer 2).
type PathRecord struct {
	PathID    int64 // auto-generated
	SessionID int64
	PathSeq   int
	HostChain string
	HopCount  int
	TTAHours  float64
}

// BreakdownRecord maps to calc_ttb_breakdown (ADR-REQ-012, Layer 3).
type BreakdownRecord struct {
	BreakdownID     int64 // auto-generated
	SessionID       int64
	AssetVid        string
	ChainPosition   string // "entrance", "intermediate", "target"
	ChainVid        string
	TTBTotal        float64
	OrientationTime float64
	TacticCount     int
	TechniqueCount  int
}

// TacticStepRecord maps to calc_ttb_tactic_steps (ADR-REQ-013, Layer 3A).
type TacticStepRecord struct {
	StepID          int64 // auto-generated by MariaDB during FlushBatch
	BreakdownIdx    int   // index into AuditBuffer.Breakdowns — resolved to BreakdownID in FlushBatch
	BreakdownID     int64 // filled in by FlushBatch after breakdown INSERT
	TacticSeq       int
	TacticID        string
	TacticName      string
	TechniqueID     string
	TechniqueName   string
	TTTHours        float64
	SwitchoverAdded bool
	CandidatesCount int
}

// TTTDetailRecord maps to calc_ttt_detail (ADR-REQ-014, Layer 4).
type TTTDetailRecord struct {
	DetailID       int64 // auto-generated by MariaDB during FlushBatch
	StepIdx        int   // index into AuditBuffer.TacticSteps — resolved to StepID in FlushBatch
	StepID         int64 // filled in by FlushBatch after step INSERT
	TechniqueID    string
	ExecMin        float64
	ExecMax        float64
	PossibleCount  int
	AppliedCount   int
	MaturityFactor float64
	FormulaCase    string // "no_mitigations", "full_coverage", "partial"
	TTTHours       float64
}

// CacheEntry maps to asset_ttb_cache (ADR-REQ-020).
type CacheEntry struct {
	AssetVid        string
	ChainPosition   string
	ComputedAt      time.Time
	NebulaHash      string
	TTBTotal        float64
	OrientationTime float64
	BreakdownJSON   string // JSON array of tactic steps with TTT detail
	IsValid         bool
}

// AuditBuffer collects all audit records for a single request (ADR-REQ-030).
// Created at the start of PathsHandler, populated during computation,
// flushed asynchronously after the HTTP response is sent.
type AuditBuffer struct {
	Session      SessionRecord
	Paths        []PathRecord
	Breakdowns   []BreakdownRecord
	TacticSteps  []TacticStepRecord
	TTTDetails   []TTTDetailRecord
	CacheEntries []CacheEntry
}

// ComputeContext is passed through the computation stack (ADR-REQ-041).
// If Audit is nil, no audit records are generated (zero overhead).
type ComputeContext struct {
	Audit *AuditBuffer
}
